const browserCatalog = {
  "version": "1.4.0",
  "tools": [
    { "name": "navigate", "description": "Navigate the active tab to an HTTP or HTTPS URL. Always use a full https:// URL.", "risk": "mutate", "inputSchema": { "type": "object", "additionalProperties": false, "required": ["url"], "properties": { "url": { "type": "string" } } } },
    { "name": "read_page", "description": "Read text content from the current page or a CSS selector. Full-page reads also return visible interactive elements with safe CSS selectors for follow-up click and type actions.", "risk": "read", "inputSchema": { "type": "object", "additionalProperties": false, "properties": { "selector": { "type": "string" }, "attribute": { "type": "string" } } } },
    { "name": "find", "description": "Find elements on the current page by visible text (optionally scoped to a CSS selector) and return real clickable references: visible text, tag, href and a working CSS selector for each match. Use this when the user names an element you have not seen yet — never guess CSS selectors from memory.", "risk": "read", "inputSchema": { "type": "object", "additionalProperties": false, "required": ["text"], "properties": { "text": { "type": "string" }, "selector": { "type": "string" } } } },
    { "name": "extract_page_content", "description": "Extract the FULL text content of the current page (or a CSS selector), including content far beyond the visible viewport, without truncation. Use this when the user asks to extract, summarize or read an entire long page.", "risk": "read", "inputSchema": { "type": "object", "additionalProperties": false, "properties": { "selector": { "type": "string" } } } },
    { "name": "structured_extract", "description": "Extract the current page or selector as JSON, CSV, or a Markdown table.", "risk": "read", "inputSchema": { "type": "object", "additionalProperties": false, "properties": { "selector": { "type": "string" }, "format": { "type": "string", "enum": ["json", "csv", "table"] } } } },
    { "name": "click", "description": "Click an element on the current page. Pass EITHER a CSS selector (use find or read_page to get one — never invent selectors from memory) OR viewport pixel coordinates { x, y } resolved with elementFromPoint. The button is left by default.", "risk": "mutate", "inputSchema": { "type": "object", "additionalProperties": false, "properties": { "selector": { "type": "string" }, "x": { "type": "integer" }, "y": { "type": "integer" }, "button": { "type": "string", "enum": ["left", "right", "middle"] } } } },
    { "name": "type", "description": "Type text into an input or textarea selected by CSS. Pass a selector from find or read_page. Set pressEnter: true to submit the field after typing (Enter) — use it when the task needs the typed value to COMMIT: adding an item to a list, sending a message, or running a search that fires on Enter.", "risk": "mutate", "inputSchema": { "type": "object", "additionalProperties": false, "required": ["selector", "text"], "properties": { "selector": { "type": "string" }, "text": { "type": "string" }, "clear": { "type": "boolean" }, "pressEnter": { "type": "boolean" } } } },
    { "name": "screenshot", "description": "Capture the visible viewport of the current HTTP or HTTPS tab.", "risk": "read", "inputSchema": { "type": "object", "additionalProperties": false, "properties": {} } },
    { "name": "tabs", "description": "List, open a new tab, switch, or close tabs in the current Chrome window. When the user explicitly asks for a new tab, use action=new; do not use navigate because navigate replaces the active tab.", "risk": "mutate", "inputSchema": { "type": "object", "additionalProperties": false, "required": ["action"], "properties": { "action": { "type": "string", "enum": ["list", "new", "switch", "close"] }, "url": { "type": "string" }, "tabId": { "type": "integer" } } } },
    { "name": "tab_group", "description": "Create, remove, assign, or unassign a Chrome tab group.", "risk": "mutate", "inputSchema": { "type": "object", "additionalProperties": false, "required": ["action"], "properties": { "action": { "type": "string", "enum": ["create", "remove", "assign", "unassign"] }, "groupId": { "type": "integer" }, "tabIds": { "type": "array", "items": { "type": "integer" } }, "title": { "type": "string" }, "color": { "type": "string", "enum": ["grey", "blue", "red", "yellow", "green", "pink", "purple", "cyan", "orange"] } } } }
  ]
}

export default browserCatalog
